baseURL="https://journey-c.github.io/"
languageCode = "en-us"
title = "Journey-C"
buildDrafts = false

googleAnalytics = "UA-181048644-1"

[permalinks]
    post = "/:filename/"

[[menu.main]]  # config your menu              # 配置目录
  name = "Github"
  weight = 30
  url = "https://github.com/journey-c"
  identifier = "github"
[[menu.main]]
  weight = 30
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "About"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "博客园"
  weight = 30
  identifier = "old_blog"
  url = "https://www.cnblogs.com/wuwangchuxin0924/"

[taxonomies]
  tag = "tags"

[params]
    toc = true
    # path to the favicon, under "static"
    favicon = "favicon.png"

    [params.logo]
    url = "yangguo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup.tableOfContents]
  startLevel = 1
  endLevel = 4
